var searchData=
[
  ['parameter_20sweep_0',['parameter sweep',['../d8/d1e/md_Documentation_2ResearcherFiles_2ParameterSweep.html#autotoc_md316',1,'Multi-Threaded Parameter Sweep'],['../d8/d1e/md_Documentation_2ResearcherFiles_2ParameterSweep.html',1,'Parameter Sweep'],['../dc/d9a/md_Documentation_2ResearcherFiles_2Researchers.html#autotoc_md331',1,'Parameter Sweep']]],
  ['parameter_20sweep_20output_1',['Parameter Sweep Output',['../d8/d1e/md_Documentation_2ResearcherFiles_2ParameterSweep.html#autotoc_md317',1,'']]],
  ['parameter_20types_2',['Parameter Types',['../d8/d03/md_Documentation_2ResearcherFiles_2Running.html#autotoc_md343',1,'']]],
  ['parameters_3',['parameters',['../da/d32/md_Documentation_2DeveloperFiles_2Tutorials_2Making__Model__Module.html#autotoc_md96',1,'3. Creating Module Parameters'],['../d0/d6b/md_Documentation_2DeveloperFiles_2Modules_2Parameters.html',1,'Module Parameters'],['../d8/d1e/md_Documentation_2ResearcherFiles_2ParameterSweep.html#autotoc_md310',1,'Module Parameters'],['../d7/dde/md_VIPRA__Behaviors_2README.html#autotoc_md491',1,'N.3. Run Time Parameters']]],
  ['parameters_20to_20help_20guide_20the_20a_20star_20algorithm_20to_20prioritize_20horizontal_20movement_20over_20vertical_20movement_20by_20hard_20coded_20values_20these_20should_20be_20created_20with_20parameters_20instead_4',['1. The cost function currently uses parameters to help guide the A Star algorithm to prioritize horizontal movement over vertical movement by hard coded values. These should be created with parameters instead.',['../da/dda/md_Modules_2Goals_2calm__goals_2pathfinding_2README.html#autotoc_md369',1,'']]],
  ['parametersweep_5',['ParameterSweep',['../d3/da4/classVIPRA_1_1ParameterSweep.html',1,'VIPRA']]],
  ['parametersweepexception_6',['ParameterSweepException',['../d0/dbf/classVIPRA_1_1ParameterSweepException.html',1,'VIPRA']]],
  ['params_7',['Module Params',['../d8/d03/md_Documentation_2ResearcherFiles_2Running.html#autotoc_md339',1,'']]],
  ['path_8',['Creation of the Path',['../da/dda/md_Modules_2Goals_2calm__goals_2pathfinding_2README.html#autotoc_md367',1,'']]],
  ['pathfinding_9',['VIPRA Pathfinding',['../da/dda/md_Modules_2Goals_2calm__goals_2pathfinding_2README.html',1,'']]],
  ['pathinggraph_10',['PathingGraph',['../d3/deb/classCALM__PATH_1_1PathingGraph.html',1,'CALM_PATH']]],
  ['pcoord_20vipra_3a_3af3d_11',['pcoord = VIPRA::f3d',['../d5/dc4/md_Documentation_2DeveloperFiles_2VIPRATypes.html#autotoc_md106',1,'']]],
  ['ped_5frandom_5ffloat_12',['ped_random_float',['../de/dc3/classBHVR_1_1DRNG.html#a119e09ac4a7ecafe0f29fa3674de71b2',1,'BHVR::DRNG']]],
  ['peddynamicsexception_13',['peddynamicsexception',['../d5/da0/classVIPRA_1_1PedDynamicsException.html#a736af6c0992bb03eb95ddcb3a14ad5f1',1,'VIPRA::PedDynamicsException::PedDynamicsException()'],['../d5/da0/classVIPRA_1_1PedDynamicsException.html',1,'VIPRA::PedDynamicsException']]],
  ['pedestrain_20loader_14',['Pedestrain Loader',['../dc/deb/md_Documentation_2DeveloperFiles_2Modules_2PedestrianLoader.html',1,'']]],
  ['pedestrian_20attributes_15',['pedestrian attributes',['../d2/d49/md_Documentation_2ResearcherFiles_2behaviors_2VIPRA__Behaviors.html#autotoc_md245',1,'C.2.6. Pedestrian Attributes'],['../d7/dde/md_VIPRA__Behaviors_2README.html#autotoc_md490',1,'N.2 Pedestrian Attributes']]],
  ['pedestrian_20colors_16',['Pedestrian Colors',['../df/d4c/md_Documentation_2ResearcherFiles_2Visualizer.html#autotoc_md354',1,'']]],
  ['pedestrian_20dynamics_20model_17',['pedestrian dynamics model',['../da/d32/md_Documentation_2DeveloperFiles_2Tutorials_2Making__Model__Module.html',1,'Making a Pedestrian Dynamics Model'],['../d1/df4/md_Documentation_2DeveloperFiles_2Modules_2PedestrianModel.html',1,'Pedestrian Dynamics Model']]],
  ['pedestrian_20loader_18',['pedestrian loader',['../d0/d30/md_README.html#autotoc_md390',1,'M.1.6. Pedestrian Loader'],['../d2/d72/md_Documentation_2DeveloperFiles_2Modules_2ModulesOverview.html#autotoc_md38',1,'M.1.6. Pedestrian Loader'],['../dd/d52/md_Documentation_2ResearcherFiles_2modules_2Modules.html#autotoc_md296',1,'Pedestrian Loader']]],
  ['pedestrian_20model_19',['pedestrian model',['../d0/d30/md_README.html#autotoc_md385',1,'M.1.1. Pedestrian Model'],['../d2/d72/md_Documentation_2DeveloperFiles_2Modules_2ModulesOverview.html#autotoc_md33',1,'M.1.1. Pedestrian Model'],['../dd/d52/md_Documentation_2ResearcherFiles_2modules_2Modules.html#autotoc_md291',1,'Pedestrian Model']]],
  ['pedestrian_20set_20',['pedestrian set',['../d2/d72/md_Documentation_2DeveloperFiles_2Modules_2ModulesOverview.html#autotoc_md36',1,'M.1.4. Pedestrian Set'],['../d0/d30/md_README.html#autotoc_md388',1,'M.1.4. Pedestrian Set'],['../d3/d85/md_Documentation_2DeveloperFiles_2Modules_2PedestrianSet.html',1,'Pedestrian Set'],['../dd/d52/md_Documentation_2ResearcherFiles_2modules_2Modules.html#autotoc_md294',1,'Pedestrian Set']]],
  ['pedestrian_20time_20step_20values_21',['O.4. Pedestrian Time Step Values',['../dc/d2d/md_Documentation_2DeveloperFiles_2Output.html#autotoc_md84',1,'']]],
  ['pedestrian_20values_22',['O.3. Pedestrian Values',['../dc/d2d/md_Documentation_2DeveloperFiles_2Output.html#autotoc_md83',1,'']]],
  ['pedestriandynamicsmodel_23',['PedestrianDynamicsModel',['../d5/dee/classVIPRA_1_1PedestrianDynamicsModel.html',1,'VIPRA']]],
  ['pedestrianloader_24',['PedestrianLoader',['../d2/de0/classVIPRA_1_1PedestrianLoader.html',1,'VIPRA']]],
  ['pedestrianloaderexception_25',['PedestrianLoaderException',['../d6/d26/classVIPRA_1_1PedestrianLoaderException.html',1,'VIPRA']]],
  ['pedestrianset_26',['PedestrianSet',['../d0/df4/classVIPRA_1_1PedestrianSet.html',1,'VIPRA']]],
  ['pedestriansetexception_27',['pedestriansetexception',['../d7/dcc/classVIPRA_1_1PedestrianSetException.html#a8ac0bbf217016c15707729c10dd1292f',1,'VIPRA::PedestrianSetException::PedestrianSetException()'],['../d7/dcc/classVIPRA_1_1PedestrianSetException.html',1,'VIPRA::PedestrianSetException']]],
  ['pedtimestepvalue_28',['pedTimestepValue',['../d7/dc9/classVIPRA_1_1Output.html#acfd5ccb5c32217696afdcc90ccc1609e',1,'VIPRA::Output']]],
  ['pedvalue_29',['pedValue',['../d7/dc9/classVIPRA_1_1Output.html#ac7f1ab58b9830731b4a12c7942aeecfd',1,'VIPRA::Output']]],
  ['percent_30',['S.5.2 Percent',['../d2/d49/md_Documentation_2ResearcherFiles_2behaviors_2VIPRA__Behaviors.html#autotoc_md180',1,'']]],
  ['perform_5faction_31',['perform_action',['../dc/d28/classBHVR_1_1Action.html#a3e7b2df9c8773ebf456f7e7246c7872c',1,'BHVR::Action']]],
  ['physically_32',['W.3. Behaviors Affect The Environment Physically',['../d7/dde/md_VIPRA__Behaviors_2README.html#autotoc_md498',1,'']]],
  ['plotting_20custom_20information_33',['Plotting Custom Information',['../df/d4c/md_Documentation_2ResearcherFiles_2Visualizer.html#autotoc_md353',1,'']]],
  ['pointmap_34',['PointMap',['../d0/d1d/structPointMap.html',1,'']]],
  ['pointmaploader_35',['PointMapLoader',['../d8/d73/classPointMapLoader.html',1,'']]],
  ['pointobstaclemap_36',['PointObstacleMap',['../db/d4f/classPointObstacleMap.html',1,'']]],
  ['policy_20model_37',['policy model',['../d0/d30/md_README.html#autotoc_md394',1,'M.2.2. Policy Model'],['../d2/d72/md_Documentation_2DeveloperFiles_2Modules_2ModulesOverview.html#autotoc_md42',1,'M.2.2. Policy Model'],['../dd/d52/md_Documentation_2ResearcherFiles_2modules_2Modules.html#autotoc_md301',1,'Policy Model']]],
  ['policymodel_38',['PolicyModel',['../d3/d60/classVIPRA_1_1PolicyModel.html',1,'VIPRA']]],
  ['positioning_20on_20the_20map_39',['Positioning on the Map',['../da/dda/md_Modules_2Goals_2calm__goals_2pathfinding_2README.html#autotoc_md363',1,'']]],
  ['pqueue_40',['pqueue',['../d8/d38/structCALM__PATH_1_1PQueue.html',1,'CALM_PATH::PQueue'],['../db/dca/structpQueue.html',1,'pQueue']]],
  ['prioritize_20horizontal_20movement_20over_20vertical_20movement_20by_20hard_20coded_20values_20these_20should_20be_20created_20with_20parameters_20instead_41',['1. The cost function currently uses parameters to help guide the A Star algorithm to prioritize horizontal movement over vertical movement by hard coded values. These should be created with parameters instead.',['../da/dda/md_Modules_2Goals_2calm__goals_2pathfinding_2README.html#autotoc_md369',1,'']]],
  ['prng_5fengine_42',['pRNG_Engine',['../d8/d8f/classVIPRA_1_1pRNG__Engine.html',1,'VIPRA']]],
  ['profiling_20tt_20for_20compiling_20in_20release_20mode_20with_20profiling_20output_43',['1. &lt;tt&gt;make profiling&lt;/tt&gt; for compiling in release mode with profiling output',['../d0/d30/md_README.html#autotoc_md377',1,'']]],
  ['ptype_44',['Ptype',['../d4/d2e/classBHVR_1_1Ptype.html',1,'BHVR']]],
  ['py_45',['visualize.py',['../df/d4c/md_Documentation_2ResearcherFiles_2Visualizer.html#autotoc_md348',1,'']]]
];
