c source code for these subroutines is available in
c routine calling potentials/forces - application specific 
      include 'model.f' 
c Lennard-Jones routines 
      include 'ljguts.f'
      include 'ljparam.f'
c general MD routines 
      include 'read_write.f' 
      include 'setin.f' 
      include 'pred_corr.f'
      include 'thermostats.f'
      include 'random_numbers.f'
c generate data 
      include 'xmol.f'
c