#ifndef DSL_HUMAN_BEHAVIOR_HPP
#define DSL_HUMAN_BEHAVIOR_HPP

#include "human_behavior.hpp"
#include "../dsl/generated/BehaviorsBaseVisitor.h"

/**
 * An implementation of a Human Behavior that reads in its behaviors from a
 * behavior file. It is also an implementation of a BehaviorsVisitor, which is
 * generated by ANTLR and reads in the data using a DSL.
 */
class DslHumanBehavior : public HumanBehavior, public BehaviorsBaseVisitor
{
    public:
        DslHumanBehavior();
        virtual ~DslHumanBehavior() = default;

        antlrcpp::Any visitStateSelector(BehaviorsParser::StateSelectorContext *ctx);
        antlrcpp::Any visitStateDeclaration(BehaviorsParser::StateDeclarationContext *ctx);
        antlrcpp::Any visitStateTransition(BehaviorsParser::StateTransitionContext *ctx);
        antlrcpp::Any visitStateAction(BehaviorsParser::StateActionContext *ctx);
        antlrcpp::Any visitConsideration(BehaviorsParser::ConsiderationContext *ctx);
};

#endif