#ifndef DSL_HUMAN_BEHAVIOR_HPP
#define DSL_HUMAN_BEHAVIOR_HPP

#include <filesystem>

#include "generated/BehaviorBaseVisitor.h"
#include "human_behavior.hpp"

class DSL_Exception : public std::runtime_error {
 public:
  DSL_Exception(const std::string& message) : std::runtime_error(message) {}
  static void Throw(const std::string& message) { throw DSL_Exception(message); }
};

/**
 * An implementation of a Human Behavior that reads in its behaviors from a
 * behavior file. It is also an implementation of a BehaviorsVisitor, which is
 * generated by ANTLR and reads in the data using a DSL.
 */
class BehaviorBuilder : public BehaviorBaseVisitor {
 public:
  HumanBehavior build(const std::filesystem::path&, VIPRA::seed);

  // TODO add in visitor methods
};

#endif