#ifndef DSL_HUMAN_BEHAVIOR_HPP
#define DSL_HUMAN_BEHAVIOR_HPP

#include "generated/BehaviorBaseVisitor.h"
#include "human_behavior.hpp"

class DSL_Exception : public std::runtime_error {
 public:
  DSL_Exception(const std::string& message) : std::runtime_error(message) {}
  static void Throw(const std::string& message) { throw DSL_Exception(message); }
};

/**
 * An implementation of a Human Behavior that reads in its behaviors from a
 * behavior file. It is also an implementation of a BehaviorsVisitor, which is
 * generated by ANTLR and reads in the data using a DSL.
 */
class DslHumanBehavior : public HumanBehavior, public BehaviorBaseVisitor {
 public:
  explicit DslHumanBehavior(const std::string& fileName);
  explicit DslHumanBehavior(const std::string& fileName, unsigned int seed);

  ~DslHumanBehavior() override = default;

  // TODO add in visitor methods

 protected:
  unsigned int seed;

 private:
  std::string behavior;
};

#endif